---
- name: Install and Configure Ansistrano Rollback
  hosts: all
  become: yes

  vars:
    ansistrano_deploy_to: "/var/www/myapp"  # Set the deployment directory here

  tasks:
    - name: Install ansistrano.rollback role via Ansible Galaxy
      ansible.builtin.command:
        cmd: ansible-galaxy install ansistrano.rollback
      changed_when: false

    - name: Ensure ansistrano.rollback role is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.ansible/roles/ansistrano.rollback"
      register: ansistrano_rollback_role

    - name: Fail if ansistrano.rollback role is not installed
      ansible.builtin.fail:
        msg: "The ansistrano.rollback role is not installed."
      when: not ansistrano_rollback_role.stat.exists

    - name: Set up Ansistrano rollback configuration
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.ansible/roles/ansistrano.rollback/defaults/main.yml"
        content: |
          ---
          # Path where the code must be deployed to
          ansistrano_deploy_to: "/"

          # Folder name for the releases
          ansistrano_version_dir: "releases"

          # Softlink name for the current release
          ansistrano_current_dir: "current"

          # Remove rolled back release?
          ansistrano_remove_rolled_back: yes

          # Rollback to this release version (previous by default)
          ansistrano_rollback_to_release: ""

          # Sends anonymous stats to the www.ansistrano.com servers
          # You can disallow it by just setting this parameter to "no" in your playbook
          ansistrano_allow_anonymous_stats: yes
        mode: '0644'
        owner: root
        group: root
      when: ansistrano_rollback_role.stat.exists
